### ISSUE TITLE
Error: ENOENT: no such file or directory, open '<script>'

### ISSUE THREAD

**Issue by vasiliy0s** [kraenhansen/dotenv-run-script#9]
After upgrading to `0.4.0` I see an error while trying to run my scripts, which were previously working.

_Notes_: I have an unusual dotenv file path because I'm working with monorepo.

```sh
vasiliy0s@lp-0632 ui % npx dotenv-run-script ../playground/.env test        
node:internal/fs/utils:347
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'test'
    at Object.openSync (node:fs:590:3)
    at Object.readFileSync (node:fs:458:35)
    at getEnv (/Users/vasiliy.telyatnikov/.npm/_npx/ac4e8c7e844599db/node_modules/dotenv-run-script/dist/index.js:86:36)
    at getSpawnOptions (/Users/vasiliy.telyatnikov/.npm/_npx/ac4e8c7e844599db/node_modules/dotenv-run-script/dist/index.js:98:14)
    at run (/Users/vasiliy.telyatnikov/.npm/_npx/ac4e8c7e844599db/node_modules/dotenv-run-script/dist/index.js:111:19)
    at Object.<anonymous> (/Users/vasiliy.telyatnikov/.npm/_npx/ac4e8c7e844599db/node_modules/dotenv-run-script/bin/dotenv-run-script:3:20)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'test'
}
```

My OS info:
```
Chip: Apple M1 Pro
macOS: Ventura 13.5.2 (22G91)
```

Node.js environment:
```sh
vasiliy0s@lp-0632 ui % node --version && npm --version    
v16.20.0
8.19.4
```

**Comment by kraenhansen** [comment]
@vasiliy0s thanks a lot for reporting this.

I had an issue in the way I had configured the NPM workspace, which meant tests were running against an old version of the package 🤦
This is now fixed together with the bug you discovered. I hope you'll take the new 0.4.1 release for a spin too 👍

**Comment by vasiliy0s** [comment]
Hi @kraenhansen,

Oh yeah, you made it working! Thank you and welcome for the issue report 🖐🏻 .
